### ISSUE TITLE
[Bug]: Apache2 and OpenSSL cannot install updates

### ISSUE THREAD

**Issue by rytecbe** [FaserF/hassio-addons#406]
### The problem

Error updating Apache2: Can't install ghcr.io/faserf/apache2-amd64:2.13.1: 500 Server Error for http+docker://localhost/v1.48/images/create?tag=2.13.1&fromImage=ghcr.io%2Ffaserf%2Fapache2-amd64&platform=linux%2Famd64: Internal Server Error ("Head "https://ghcr.io/v2/faserf/apache2-amd64/manifests/2.13.1": denied")

### What version of Home Assistant Core has the issue?

2025.5.1

### What version of the addon has the issue?

2.13.0

### What type of installation are you running?

Home Assistant OS

### Add-On causing the issue

Apache2

### Log information

```txt

```

**Comment by FaserF** [comment]
Fixed 15 minutes ago, please give it another try

**Comment by neildsb** [comment]
not sure if its linked?

Error updating Apache2 Minimal: Can't install ghcr.io/faserf/apache2-minimal-amd64:2.12.5: 500 Server Error for http+docker://localhost/v1.48/images/create?tag=2.12.5&fromImage=ghcr.io%2Ffaserf%2Fapache2-minimal-amd64&platform=linux%2Famd64: Internal Server Error ("Head "https://ghcr.io/v2/faserf/apache2-minimal-amd64/manifests/2.12.5": denied")

**Comment by rytecbe** [comment]
> Fixed 15 minutes ago, please give it another try

Sorry, still same failure.

Best regards

**Comment by dragorex71** [comment]
Same problem, just tried.
It happens every update and fix after a while

**Comment by ShonP40** [comment]
Still getting the same error

Was getting it for every update but it usually fixed itself after 24 hours...

**Comment by pmeHA** [comment]
Same error:

Error updating Apache2: Can't install ghcr.io/faserf/apache2-aarch64:2.13.1: 500 Server Error for http+docker://localhost/v1.48/images/create?tag=2.13.1&fromImage=ghcr.io%2Ffaserf%2Fapache2-aarch64&platform=linux%2Farm64: Internal Server Error ("Head "https://ghcr.io/v2/faserf/apache2-aarch64/manifests/2.13.1": denied")

**Comment by FaserF** [comment]
Fixed with the latest release for all addons . The update is still building and should be available within 15 minutes.
